library(ggplot2)
library(readxl)
delta <- read_excel("/Users/andrew/Library/CloudStorage/Box-Box/Personal/Postdoc_Purdue/Towhee/Black_analysis/k.xlsx")
ggplot(delta,aes(x=K,y=`mean(|L"(K)|)/stdev[L(K)]")`))+geom_line(color="black") + geom_point(color="cadetblue",size=6)+theme_classic()+ylab("∆K")
ggsave("~/delta.svg")
